const Decorationdata = [
    {
        id:1,
        img:"../image/d1.jpg",
        name:"Weddings Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹25,000",
        Onwards:"Onwards",
        point: "1.5",
        review: "12 reviews",
        starimg:"./image/star.png",
    },
    {
        id:2,
        img:"../image/d2.webp",
        name:"Ajmeri pink Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹45,000",
        Onwards:"Onwards",
        point: "2.5",
        starimg: "./image/star.png",
        review: "13 reviews",

    },
    {
        id:3,
        img:"../image/d3.jpg",
        name:"River side  Decoration",
        location:"goa",
        text:"staring price For Decorate",
        price:"₹50,000",
        Onwards:"Onwards",
        point: "1.5",
        starimg:"./image/star.png",
        review: "7 reviews",
    },
    {
        id:4,
        img:"../image/d4.jpg",
        name:"Engagement Decoration",
        location:"piplod,surat",
        text:"staring price For Decorate",
        price:"₹6,000",
        Onwards:"Onwards",
        point: "1.7",
        starimg:"./image/star.png",
    
        review: "12 reviews",

    },
    {
        id:5,
        img:"../image/d5.jpeg",
        name:"pink-red   Decoration",
        location:"kamrej,surat",
        text:"staring price For Decorate",
        price:"₹56,000",
        Onwards:"Onwards",
        point: "1.6",
        starimg:"./image/star.png",
        review: "16 reviews",
    
    },
    {
        id:6,
        img:"../image/d6.webp",
        name:" Engagement Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹10,000",
        Onwards:"Onwards",
        review: "14 reviews",
        starimg:"./image/star.png",
        point: "2.5",
    },
    {
        id:7,
        img:"../image/d7.jpg",
        name:"Real flowers  Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹13,000",
        Onwards:"Onwards",
        point: "1.7",
        review: "21 reviews",
        starimg:"./image/star.png",

    },
    {
        id:8,
        img:"../image/d8.jpg",
        name:"Pink-White latest  Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹18,000",
        Onwards:"Onwards",
        point: "1.5",
        review: "8 reviews",
        starimg:"./image/star.png",
    
    },
    {
        id:9,
        img:"../image/d9.jpeg",
        name:"Full Flowers Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹10,000",
        Onwards:"Onwards",
        point: "0.3",
        starimg:"./image/star.png",
    
        review: "4 reviews",
    },
    {
        id:10,
        img:"../image/d10.jpg",
        name:"Lighting white Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹20,000",
        Onwards:"Onwards",
        point: "0.2",
        starimg:"./image/star.png",
    
        review: "12 reviews",

    },
    {
        id:11,
        img:"../image/d11.jpg",
        name:"White Flowers Decoration",
        location:"vip,surat",
        text:"staring price For Decorate",
        price:"₹15,000",
        Onwards:"Onwards",
        point: "1.2",
        starimg:"./image/star.png",
    
        review: "6 reviews",
    },
    {
        id:12,
        img:"../image/d12.jpg",
        name:"Engagement Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹65,000",
        Onwards:"Onwards",
        point: "0.5",
        starimg:"./image/star.png",
    
        review: "2 reviews",
    },
    {
        id:13,
        img:"../image/d13.webp",
        name:"Engagement photography",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹7,000",
        Onwards:"Onwards",
        point: "1.2",
        starimg:"./image/star.png",
    
        review: "8 reviews",
    },
    {
        id:14,
        img:"../image/d14.jpg",
        name:"Marrige Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹7,000",
        Onwards:"Onwards",
        point: "1.5",
        starimg:"./image/star.png",
    
        review: "9 reviews",
    },
    {
        id:15,
        img:"../image/d15.jpg",
        name:"Lighting Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹12,000",
        Onwards:"Onwards",
        point: "2.3",
        starimg:"./image/star.png",
    
        review: "17 reviews",

    },
    {
        id:16,
        img:"../image/d16.jpg",
        name:"Multi-color Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹67,00",
        Onwards:"Onwards",
        point: "0.2",
        starimg:"./image/star.png",
    
        review: "12 reviews",
    },
    {
        id:17,
        img:"../image/d17.webp",
        name:"Ocean Marrige Decoration",
        location:"goa",
        text:"staring price For Decorate",
        price:"₹50,000",
        Onwards:"Onwards",
        point: "1.5",
        starimg:"./image/star.png",
    
        review: "13 reviews",
    },
    {
        id:18,
        img:"../image/d18.jpeg",
        name:"Wedding Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹15,000",
        Onwards:"Onwards",
        point: "1.8",
        starimg:"./image/star.png",
    
        review: "34 reviews",

    },
    {
        id:19,
        img:"../image/d19.jpeg",
        name:"River-said  Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹16,000",
        Onwards:"Onwards",
        starimg:"./image/star.png",

        point: "0.5",
        review: "14 reviews",

    },
    {
        id:20,
        img:"../image/d20.jpeg",
        name:"Best marrige Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹29,000",
        Onwards:"Onwards",
        starimg:"./image/star.png",

        point: "1.0",
        review: "7 reviews",

    },
    {
        id:21,
        img:"../image/d21.jpg",
        name:" Weddings Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹25,000",
        Onwards:"Onwards",
        point: "1.2",
        starimg:"./image/star.png",
    
        review: "12 reviews",

    },
    {
        id:22,
        img:"../image/d22.png",
        name:"Ajmeri white Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹45,000",
        Onwards:"Onwards",
        point: "1.5",
        starimg:"./image/star.png",
    
        review: "15 reviews",
    },
    {
        id:23,
        img:"../image/d23.jpg",
        name:"River side  Decoration",
        location:"goa",
        text:"staring price For Decorate",
        price:"₹50,000",
        Onwards:"Onwards",
        point: "1.3",
        starimg:"./image/star.png",
    
        review: "13 reviews",
    },
    {
        id:24,
        img:"../image/d24.webp",
        name:"Engagement  Decoration",
        location:"piplod,surat",
        text:"staring price For Decorate",
        price:"₹6,000",
        Onwards:"Onwards",
        point: "0.7",
        starimg:"./image/star.png",
    
        review: "17 reviews",
    },
    {
        id:25,
        img:"../image/d25.jpeg",
        name:"pink-red   Decoration",
        location:"kamrej,surat",
        text:"staring price For Decorate",
        price:"₹56,000",
        Onwards:"Onwards",
        point: "1.5",
        starimg:"./image/star.png",
    
        review: "9 reviews",

    },
    {
        id:26,
        img:"../image/d26.jpg",
        name:"Night  Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹10,000",
        Onwards:"Onwards",
        point: "0.7",
        starimg:"./image/star.png",
    
        review: "17 reviews",
    },
    {
        id:27,
        img:"../image/d27.jpg",
        name:"  Engagement Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹13,000",
        Onwards:"Onwards",
        starimg:"./image/star.png",

        point: "1.5",
        review: "12 reviews",
    },
    {
        id:28,
        img:"../image/d28.webp",
        name:"Pink-White  Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹18,000",
        Onwards:"Onwards",
        point: "0.5",
        starimg:"./image/star.png",
    
        review: "12 reviews",

    },
    {
        id:29,
        img:"../image/d29.jpg",
        name:"Full Flowers Decoration",
        location:"vesu,surat",
        text:"staring price For Decorate",
        price:"₹10,000",
        Onwards:"Onwards",
        starimg:"./image/star.png",

        point: "1.3",
        review: "14 reviews",

    },
    {
        id:30,
        img:"../image/d30.jpeg",
        name:"Lighting white Decoration",
        location:"surat",
        text:"staring price For Decorate",
        price:"₹20,000",
        Onwards:"Onwards",
        point: "1.5",
        starimg:"./image/star.png",
    
        review: "12 reviews",

    },

]

export default Decorationdata;