const pdata = [
  {
    id: 1,
    img: "../image/photo1.jpg",
    name: "BH Production House",
    starimg: "./image/star.png",
    city: "VIP Road,surat",
    point: "0.5",
    review: "2 reviews",
    text: "photo+video",
    price: "₹50,000",
    day: " per day",
  },
  {
    id: 2,
    img: "../image/photo2.jpg",
    name: "MS photography",
    point: "2.5",
    starimg: "./image/star.png",
    review: "13 reviews",
    city: "Adajan, Surat",
    text: "photo+video",
    price: "₹45,000",
    day: "per day",
  },
  {
    id: 3,
    img: "../image/photo3.jpg",
    name: "Radhey photography",
    point: "1.5",
    starimg:"./image/star.png",
    review: "7 reviews",
    city: "Criston goa",
    text: "photo+video",
    price: "₹52,000",
    day: "per day",
  },
  {
    id: 4,
    img: "../image/photo4.jpg",
    name: "Ministry Of Memories",
    point: "1.7",
    starimg:"./image/star.png",

    review: "12 reviews",
    city: "Noida Delhi",
    text: "photo+video",
    price: "₹55,000",
    day: "per day",
  },
  {
    id: 5,
    img: "../image/photo5.jpg",
    name: "RD The WedLock ",
    point: "1.6",
    starimg:"./image/star.png",
    review: "16 reviews",

    city: "Vesu, Surat",
    text: "photo+video",
    price: "₹48,000",
    day: "per day",
  },
  {
    id: 6,
    img: "../image/photo6.jpg",
    name: "Hari Studio",
    review: "14 reviews",
    starimg:"./image/star.png",
    point: "2.5",
    
    text: "photo+video",
    city: "VIP, Surat",
    price: "₹57,500",
    day: "per day",
  },
  {
    id: 7,
    img: "../image/photo7.jpg",
    name: "The castila House",
    point: "1.7",
    review: "21 reviews",
    starimg:"./image/star.png",
    city: "jaipur",

    text: "photo+video",
    price: "₹49,300",
    day: "per day",
  },
  {
    id: 8,
    img: "../image/photo8.jpg",
    name: "The real House",
    city: "goa",
    point: "1.5",
    review: "8 reviews",
    starimg:"./image/star.png",
    text: "photo+video",

    price: "₹51,000",
    day: "per day",
  },
  {
    id: 9,
    img: "../image/photo9.jpg",
    name: "BH Production House",
    city: "jaipur",
    point: "0.3",
    starimg:"./image/star.png",

    review: "4 reviews",
    text: "photo+video",
    price: "₹38,000",
    day: "per day",
  },
  {
    id: 10,
    img: "../image/photo10.jpg",
    name: "BH Production House",
    city: "Hari village, Surat",
    point: "0.2",
    starimg:"./image/star.png",

    review: "12 reviews",
    text: "photo+video",
    price: "₹58,700",
    day: "per day",
  },
  {
    id: 11,
    img: "../image/photo11.jpg",
    name: "candid photography",
    city: "vesu, Surat",
    point: "1.2",
    starimg:"./image/star.png",

    review: "6 reviews",
    text: "photo+video",
    price: "₹60,000",
    day: "per day",
  },
  {
    id: 12,
    img: "../image/photo12.jpg",
    name: "Wedding picture",
    city: "Dumas Road, Surat",
    point: "0.5",
    starimg:"./image/star.png",

    review: "2 reviews",
    text: "photo+video",
    price: "₹56,500",
    day: "per day",
  },
  {
    id: 13,
    img: "../image/photo13.jpg",
    name: "Radhey photos",
    city: "surat",
    point: "1.2",
    starimg:"./image/star.png",

    review: "8 reviews",
    text: "photo+video",
    price: "₹52,500",
    day: "per day",
  },
  {
    id: 14,
    img: "../image/photo14.jpg",
    name: "RV The WedLook ",
    city: "Jaipur",
    point: "1.5",
    starimg:"./image/star.png",

    review: "9 reviews",
    text: "photo+video",
    price: "₹70,000",
    day: "per day",
  },
  {
    id: 15,
    img: "../image/photo15.jpg",
    name: "Wedding picture",
    city: "Goa",
    point: "2.3",
    starimg:"./image/star.png",

    review: "17 reviews",
    text: "photo+video",
    price: "₹50,000",
    day: "per day",
  },
  {
    id: 16,
    img: "../image/photo16.jpg",
    name: "The Wedding villa",
    city: "Vesu, Surat",
    point: "0.2",
    starimg:"./image/star.png",

    review: "12 reviews",
    text: "photo+video",
    price: "₹52,300",
    day: "per day",
  },
  {
    id: 17,
    img: "../image/photo17.jpeg",
    name: "The wedding House",
    city: "Jaipur",
    point: "1.5",
    starimg:"./image/star.png",

    review: "13 reviews",
    text: "photo+video",
    price: "₹50,300",
    day: "per day",
  },
  {
    id: 18,
    img: "../image/photo18.jpg",
    name: "RV photography",
    city: "VIP, Surat",
    point: "1.8",
    starimg:"./image/star.png",

    review: "34 reviews",
    text: "photo+video",
    price: "₹60,000",
    day: "per day",
  },
  {
    id: 19,
    img: "../image/photo19.jpg",
    name: "The Wedding villa",
    city: "Goa",
    starimg:"./image/star.png",

    point: "0.5",
    review: "14 reviews",
    text: "photo+video",
    price: "₹50,000",
    day: "per day",
  },
  {
    id: 20,
    img: "../image/photo20.jpg",
    name: "BH Production House",
    city: "Jaipur",
    starimg:"./image/star.png",

    point: "1.0",
    review: "7 reviews",
    text: "photo+video",
    price: "₹50,000",
    day: "per day",
  },
  {
    id: 21,
    img: "../image/photo21.webp",
    name: "BH Production House",
    city: "Jaipur",
    point: "1.2",
    starimg:"./image/star.png",

    review: "12 reviews",
    text: "photo+video",
    price: "₹50,000",
    day: "per day",
  },
  {
    id: 22,
    img: "../image/photo22.webp",
    name: "Wedding picture",
    city: "Dumas Road, Surat",
    point: "1.5",
    starimg:"./image/star.png",

    review: "15 reviews",
    text: "photo+video",
    price: "₹56,500",
    day: "per day",
  },
  {
    id: 23,
    img: "../image/photo23.webp",
    name: "Radhey photos",
    city: "surat",
    point: "1.3",
    starimg:"./image/star.png",

    review: "13 reviews",
    text: "photo+video",
    price: "₹52,500",
    day: "per day",
  },
  {
    id: 24,
    img: "../image/photo24.webp",
    name: "RV The WedLook villa",
    city: "Jaipur",
    point: "0.7",
    starimg:"./image/star.png",

    review: "17 reviews",
    text: "photo+video",
    price: "₹70,000",
    day: "per day",
  },
  {
    id: 25,
    img: "../image/photo25.webp",
    name: "Wedding picture",
    city: "Goa",
    point: "1.5",
    starimg:"./image/star.png",

    review: "9 reviews",
    text: "photo+video",
    price: "₹50,000",
    day: "per day",
  },
  {
    id: 26,
    img: "../image/photo26.webp",
    name: "The Wedding villa",
    city: "Vesu, Surat",
    point: "0.7",
    starimg:"./image/star.png",

    review: "17 reviews",
    text: "photo+video",
    price: "₹52,300",
    day: "per day",
  },
  {
    id: 27,
    img: "../image/photo27.jpg",
    name: "The wedding House",
    city: "Jaipur",
    starimg:"./image/star.png",

    point: "1.5",
    review: "12 reviews",
    text: "photo+video",
    price: "₹50,300",
    day: "per day",
  },
  {
    id: 28,
    img: "../image/photo28.jpg",
    name: "RV photography",
    city: "VIP, Surat",
    point: "0.5",
    starimg:"./image/star.png",

    review: "12 reviews",
    text: "photo+video",
    price: "₹60,000",
    day: "per day",
  },
  {
    id: 29,
    img: "../image/photo29.jpg",
    name: "The castila House",
    city: "jaipur",
    starimg:"./image/star.png",

    point: "1.3",
    review: "14 reviews",
    text: "photo+video",
    price: "₹49,300",
    day: "per day",
  },
  {
    id: 30,
    img: "../image/photo30.jpg",
    name: "The real House",
    city: "goa",
    point: "1.5",
    starimg:"./image/star.png",

    review: "12 reviews",
    text: "photo+video",
    price: "₹51,000",
    day: "per day",
  },
];

export default pdata;
